### ISSUE TITLE
Cannot add device Stanmore II bluetooth

### ISSUE THREAD

**Issue by sveinungre** [andreasvikke/marshall-speaker#2]
I just tried the new app to add Stanmore II bluetooth device, the device is located 2 meter away from the Homey Pro 2023.
When I try to add the device I get "No new devices found". 

Diagnostics d4e00cb6-7be2-49e8-924f-9dd8c84e33ec.
Thanks.

**Comment by andreasvikke** [comment]
@sveinungre, sorry for the late repsone, i ahve bene away on vacation :)

I cannot reproduce the error your getting, but lets try some stuff out!
First off, have you connected the speaker to the same WIFI router as the homey? [Guide](https://support.marshallheadphones.com/hc/en-us/articles/115005130625-How-to-Stanmore-Multi-Room-Wi-Fi-Streaming-from-Chromecast-built-in)

If this is the case, can you find the local ip of the speaker (from the router) and connect to it in your browser?

If so can you please send me a report from the report tap of the Marshall speaker? 
This report contains a version.txt where i can see the information of the MDNS protocol, that is used for searching the wifi for the marshall speakers. Maybe the MDNS information has changed from Woburn to Stanmore :)

**Comment by sveinungre** [comment]
This is a Bluetooth speaker, it doesn't support wifi. Is yours wifi? I checked Marshall page and I thought your speaker were also Bluetooth?

Sveinung
________________________________

**Comment by andreasvikke** [comment]
Aah, this is why then. 
This app is currently only supporting Marshall WIFI speakers...

I will look into trying to connect to Bluetooth speakers when i got the time, and will let you know as soon as progress is made :)

**Comment by sveinungre** [comment]
Yup. Maybe the information for the app could state that only Wi-Fi devices are supported? Thanks for replying and I hope you had a good vacation.

Sveinung
________________________________

**Comment by andreasvikke** [comment]
I will update the description with this information.

I have also just looked a bit into it, and it sadly dosn't seem possible for a Homey to pair with a blutooth speaker... I will keep the issue open and investigate more.

**Comment by sveinungre** [comment]
Great thanks again.

Sveinung
________________________________
